Online_Boutique/Online_Boutique/Controllers/MyCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Online_Boutique.Models.MyModels;
using System.Web.Script.Serialization;

namespace Online_Boutique.Controllers
{
    public class MyCartController : Controller
    {
        Online_BoutiqueEntities db = new Online_BoutiqueEntities();
        // GET: MyCart
        public ActionResult Index()
        {
            return View();
        }

        //lay gio hang
        public List<GioHang> LayGioHang()   //lay cai session ra
        {
            List<GioHang> listgh = Session["cart"] as List<GioHang>;

            // viet như thế này nếu session nó chưa tồn tại thì ép kiểu sẽ lỗi
            //còn viết như trên kia, nếu  session chưa tồn tại thì trả về null
            //List<GioHang> listgh = (List<GioHang>)Session["cart"]
            if (listgh == null)
            {
                //neu gio hang chua ton tai thi khoi tao list gio hang (session gio hang)
                listgh = new List<GioHang>();
                Session["cart"] = listgh;
            }
            return listgh; 
        }


        //thêm giỏ hàng
        public ActionResult ThemGioHang(int masp,string url)
        {
            SanPham sp = db.SanPhams.SingleOrDefault(x => x.masp == masp);
            if(sp==null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //lay ra session gio hang
            int contcart = 0;
            List<GioHang> listgh = LayGioHang();
            foreach(GioHang item in listgh)
            {
                contcart += item.slmuasp;
                
            }
            Session["ls"] = contcart + 1;
            GioHang sp2 = listgh.Find(x => x.masp == masp);
            if(sp2==null)
            {
                sp2 = new GioHang(masp);
                listgh.Add(sp2);
                return Redirect(Request.UrlReferrer.ToString());
                //bản chất của return Redirect(url); vẫn giống câu lệnh trên và vẫn bị load lại trang
            }
            else
            {
                sp2.slmuasp++;
                return Redirect(Request.UrlReferrer.ToString());
            }
        }

        // cập nhật giỏ hàng
        public JsonResult CapNhatGioHang(string cartModel)
        {
            var cart = new JavaScriptSerializer().Deserialize<List<GioHang>>(cartModel);
            var ls = Session["cart"] as List<GioHang>;
            foreach(var item in ls)
            {
               var sp = cart.SingleOrDefault(n=>n.masp == item.masp);
               if(sp!=null)
                {
                    item.slmuasp = sp.slmuasp;
                }
            }
            Session["cart"] = ls;
            return Json(new { status = true });
        }
        

        //xoa gio hang
        public ActionResult XoaGioHang(int masp)
        {
            List<GioHang> listgh = LayGioHang();
            GioHang sp = listgh.SingleOrDefault(x => x.masp == masp);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            else
            {
                listgh.Remove(sp);
            }
            if(listgh.Count==0)
            {
                return RedirectToAction("Index", "MyHome");
            }
            return RedirectToAction("GioHang");

        }

        //xay dung trang gio hang
        public ActionResult GioHang()
        {
            if (Session["cart"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                List<GioHang> listgh = LayGioHang();
                ViewBag.tongtien = TongThanhTien();
                return View(listgh);
            }
        }


        // tinh tong sl mua va thanh tien

        public int TongSLMua()
        {
            int tongslmua = 0;
            List<GioHang> listgh = Session["cart"] as List<GioHang>;
            if (listgh != null)
                tongslmua = listgh.Sum(x => x.slmuasp);
            return tongslmua;
        }
        public ActionResult XoaTatCaGioHang()
        {
            List<GioHang> listgh = Session["cart"] as List<GioHang>;
            if(listgh != null)
            {
                Session.Remove("cart");
                
            }
            return RedirectToAction("Index", "MyHome");
        }
        public Nullable<int> TongThanhTien()
        {
            Nullable<int> tongthanhtien = 0;
            List<GioHang> listgh = Session["cart"] as List<GioHang>;
            if (listgh != null)
                tongthanhtien = listgh.Sum(x => x.thanhtien);
          
            return tongthanhtien;
        }

        
    }
}

Online_Boutique/Online_Boutique/Controllers/MyHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Online_Boutique.Models.MyModels;


namespace Online_Boutique.Controllers
{
    
    public class MyHomeController : Controller
    {
        Online_BoutiqueEntities db = new Online_BoutiqueEntities();
        // GET: MyHome
        public ActionResult Index()
        {
            var listnewsp = db.SanPhams.OrderBy(x=>x.ngaynhapsp).Take(12).ToList();
            return View(listnewsp);
        }

        public PartialViewResult HeaderPartial(string gt)
        {
            object listrecord;
            List<GioHang> ls = Session["cart"] as List<GioHang>;

               if(ls != null)
            {
                ViewBag.soluong = ls.Count;
                ViewBag.tongtien = ls.Sum(x => x.thanhtien);
            }
               else
            {
                ViewBag.soluong = 0;
                ViewBag.tongtien = 0;
            }
           // if (gt == "nu")

            listrecord = db.LoaiSanPhams.Where(x => x.gioitinh == "nữ").OrderBy(x => x.tenloaisp).ToList();
          //  else
            
           //      listrecord = db.LoaiSanPhams.Where(x => x.gioitinh == "nam").OrderBy(x => x.tenloaisp).ToList();
            
            return PartialView(listrecord);
               
            
        }

        public PartialViewResult FooterPartial()
        {
            return PartialView();
        }
        public PartialViewResult ContainerPartial()
        {
            return PartialView(db.SanPhams.Take(8).ToList());
        }

    }
}

Online_Boutique/Online_Boutique/Controllers/MyProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Online_Boutique.Models.MyModels;
using PagedList;
using PagedList.Mvc;


namespace Online_Boutique.Controllers
{
    public class MyProductsController : Controller
    {
        Online_BoutiqueEntities db = new Online_BoutiqueEntities();
        // GET: MyProducts
        public ActionResult Index()
        {
            return View();
        }
        public ViewResult LoaiSP(int? page, int maloaisp = 0, int pagesize = 2)
        {
            //tao bien so trang
            //???????? mấy dấu ? là thế nào?
            //nếu ko đủ số sp trên 1 trang thì pagenumber=1 ???
            int pagenumber = (page ?? 2);

            if (page <= 0)    //bat loi neu thang user sửa đường dẫn page<=0
                pagenumber = 2;



            LoaiSanPham lsp = db.LoaiSanPhams.SingleOrDefault(x => x.maloaisp == maloaisp);
            if (lsp == null)
            {
                Response.StatusCode = 404;
                return null;
            }   
            else
            {
                ViewBag.mlsp = lsp.maloaisp;

                //bắt lỗi nếu thằng user sửa url page > @Model.PageCount
                List<SanPham> listsp = db.SanPhams.Where(x => x.maloaisp == lsp.maloaisp).ToList();
                int sumsp=0;
                for(int  i=1;i<=page;i++)
                {
                    sumsp += pagesize;
                    if(sumsp>= listsp.Count())
                    {
                        pagenumber = i;
                        break;
                    }
                    
                }
                //////////////////////////////

                return View(db.SanPhams.Where(x => x.maloaisp == lsp.maloaisp).OrderBy(x => x.ngaynhapsp).ToPagedList(pagenumber, pagesize));
             
            }
        }

        public ViewResult ChiTietSP(int masp)
        {
            SanPham sp = db.SanPhams.SingleOrDefault(x => x.masp == masp);
            if (sp == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            else
                return View(sp);
        }
 
    }
}

Online_Boutique/Online_Boutique/Controllers/MySearchProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Online_Boutique.Models.MyModels;
using PagedList;
using PagedList.Mvc;

namespace Online_Boutique.Views.MyProducts
{
    public class MySearchProductsController : Controller
    {
        Online_BoutiqueEntities db = new Online_BoutiqueEntities();
        // GET: TimKiemSP
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult KetQuaTimKiem(int? page, FormCollection f, int pagesize = 2)
        {
            string chuoitk = f["txttimkiem"].ToString();
            List<SanPham> listkqtk = db.SanPhams.Where(x => x.tensp.Contains(chuoitk)).ToList();

            int pagenumber = (page ?? 1);
            ViewBag.tukhoa = chuoitk;

            if (listkqtk.Count() == 0)
            {
                ViewBag.thongbao = "Không tìm thấy sản phẩm nào phù hợp với \"" + chuoitk + "\"";
                return View(listkqtk.ToPagedList(pagenumber, pagesize));
            }
            else
            {

                ViewBag.thongbao = "Tìm thấy " + listkqtk.Count() + " sản phẩm phù hợp với \"" + chuoitk + "\"";
                return View(listkqtk.OrderBy(x => x.tensp).ToPagedList(pagenumber, pagesize));
            }

        }

        [HttpGet]
        public ActionResult KetQuaTimKiem(int? page, string keyword, int pagesize = 1)
        {

            List<SanPham> listkqtk = db.SanPhams.Where(x => x.tensp.Contains(keyword)).ToList();

            ViewBag.tukhoa = keyword;   // bởi vì khi chuyển sang action khác thì cái ViewBag.tukhoa trên kia bị mất đi

            int pagenumber = (page ?? 1);

            if (page <= 0)    //bat loi neu thang user sửa đường dẫn page<=0
                pagenumber = 1;



            if (listkqtk.Count() == 0)
            {
                ViewBag.thongbao = "Không tìm thấy sản phẩm nào phù hợp với \"" + keyword + "\"";
                return View(listkqtk.ToPagedList(pagenumber, pagesize));
            }
            else
            {

                //bắt lỗi nếu thằng user sửa url page > @Model.PageCount

                int sumsp = 0;
                for (int i = 1; i <= page; i++)
                {
                    sumsp += pagesize;
                    if (sumsp >= listkqtk.Count())
                    {
                        pagenumber = i;
                        break;
                    }

                }

                ViewBag.thongbao = "Tìm thấy " + listkqtk.Count() + " sản phẩm phù hợp với \"" + keyword + "\"";
                return View(listkqtk.OrderBy(x => x.tensp).ToPagedList(pagenumber, pagesize));


            }
        }
    }
}

Online_Boutique/Online_Boutique/Controllers/MyUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Online_Boutique.Models.MyModels;

namespace Online_Boutique.Controllers
{
    public class MyUsersController : Controller
    {
        Online_BoutiqueEntities db = new Online_BoutiqueEntities();
        // GET: MyUsers
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult DangKi()
        {

            return View();
        }

        [HttpPost]
        public ActionResult DangKi(KhachHang kh)
        {
            kh.quyenhan = "user";
            db.KhachHangs.Add(kh);
            db.SaveChanges();
            return RedirectToAction("Index","MyHome");
        }

        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangNhap(FormCollection fc)
        {
            //FormCollection la cai deo gi
            string username = fc["txttk"].ToString();
            string password = fc["txtmk"].ToString();
            // hoac username = fc.Get("txttk").ToString();
            //      password = fc.Get("txtmk").ToString();
            KhachHang kh = db.KhachHangs.SingleOrDefault(x => x.tentaikhoan == username && x.matkhau == password);
            if (kh != null)
            {
                ViewBag.thongbao = "Đăng nhập thành công";
                Session["user"] = kh;
                Session["username"] = kh.tentaikhoan;
                Session["email"] = kh.email;
                Session["DiaChi"] = kh.Diachi;
                Session["SDT"] = kh.sdt;
                Session["fullname"] = kh.hoten;

                if (kh.quyenhan == "user")

                    return RedirectToAction("Index", "MyHome");
                else
                    return RedirectToAction("DanhSachSP", "MyManageProducts");
          
                //lưu cái tai khoan vừa đăng nhập thành công lại
                
            }
            else
                ViewBag.thongbao = "Tên tài khoản hoặc mật khẩu không đúng";
            return View();
        }
    }
}

Online_Boutique/Online_Boutique/Views/MyHome/ContainerPartial.cshtml
@model List<Online_Boutique.Models.MyModels.SanPham>

<div class="other-products">
    <div class="container">
        <h3 class="like text-center">Sản Phẩm Được Yêu Thích</h3>
        <ul id="flexiselDemo3">
            @{
                foreach (var item in Model)
                {
                    <li>
                        <a href="@Url.Action("ChiTietSP","MyProducts", new {@masp= @item.masp })"><img src="@Url.Content("~/HinhAnh/nu/"+@item.anhsp)" class="img-responsive anhsp" alt="" /></a>
                        <div class="product liked-product simpleCart_shelfItem">
                            <a class="like_name" href="@Url.Action("ChiTietSP","MyProducts", new {@masp= @item.masp })">@item.tensp</a>
                            <p><a class="item_add" href="@Url.Action("ThemGioHang","MyCart",new {@masp= @item.masp, @url= Request.Url.ToString() })"><i></i> <span class="item_price">@item.giabansp VND</span></a></p>
                        </div>
                    </li>
                }
            }
          
           
        </ul>
        <script type="text/javascript">
					 $(window).load(function() {
						$("#flexiselDemo3").flexisel({
							visibleItems: 4,
							animationSpeed: 1000,
							autoPlay: true,
							autoPlaySpeed: 3000,
							pauseOnHover: true,
							enableResponsiveBreakpoints: true,
					    	responsiveBreakpoints: {
					    		portrait: {
					    			changePoint:480,
					    			visibleItems: 1
					    		},
					    		landscape: {
					    			changePoint:640,
					    			visibleItems: 2
					    		},
					    		tablet: {
					    			changePoint:768,
					    			visibleItems: 3
					    		}
					    	}
					    });

					});
        </script>
        <script type="text/javascript" src="~/Content/web/js/jquery.flexisel.js"></script>
    </div>
</div>

Online_Boutique/Online_Boutique/Views/MyHome/FooterPartial.cshtml
<div class="news-letter">
    <div class="container">
        <div class="join">
            <li><h6>JOIN OUR MAILING LIST</h6></li>
            <div class="sub-left-right">
                <form>
                    <input type="text" value="Enter Your Email Here" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter Your Email Here';}" />
                    <input type="submit" value="SUBSCRIBE" />
                </form>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<div class="footer">
    <div class="container">
        <div class="footer_top">
            <div class="span_of_4">
                <div class="col-md-3 span1_of_4">
                    <h4>Shop</h4>
                    <ul class="f_nav">
                        <li><a href="#">new arrivals</a></li>
                        <li><a href="#">men</a></li>
                        <li><a href="#">women</a></li>
                        <li><a href="#">accessories</a></li>
                        <li><a href="#">kids</a></li>
                        <li><a href="#">brands</a></li>
                        <li><a href="#">trends</a></li>
                        <li><a href="#">sale</a></li>
                        <li><a href="#">style videos</a></li>
                    </ul>
                </div>
                <div class="col-md-3 span1_of_4">
                    <h4>help</h4>
                    <ul class="f_nav">
                        <li><a href="#">frequently asked  questions</a></li>
                        <li><a href="#">men</a></li>
                        <li><a href="#">women</a></li>
                        <li><a href="#">accessories</a></li>
                        <li><a href="#">kids</a></li>
                        <li><a href="#">brands</a></li>
                    </ul>
                </div>
                <div class="col-md-3 span1_of_4">
                    <h4>account</h4>
                    <ul class="f_nav">
                        <li><a href="account.html">login</a></li>
                        <li><a href="register.html">create an account</a></li>
                        <li><a href="#">create wishlist</a></li>
                        <li><a href="checkout.html">my shopping bag</a></li>
                        <li><a href="#">brands</a></li>
                        <li><a href="#">create wishlist</a></li>
                    </ul>
                </div>
                <div class="col-md-3 span1_of_4">
                    <h4>popular</h4>
                    <ul class="f_nav">
                        <li><a href="#">new arrivals</a></li>
                        <li><a href="#">men</a></li>
                        <li><a href="#">women</a></li>
                        <li><a href="#">accessories</a></li>
                        <li><a href="#">kids</a></li>
                        <li><a href="#">brands</a></li>
                        <li><a href="#">trends</a></li>
                        <li><a href="#">sale</a></li>
                        <li><a href="#">style videos</a></li>
                        <li><a href="#">login</a></li>
                        <li><a href="#">brands</a></li>
                    </ul>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="cards text-center">
            <img src="~/Content/web/images/cards.jpg" alt="" />
        </div>
        <div class="copyright text-center">
            <p>© 2015 Eshop. All Rights Reserved | Design by   <a href="http://w3layouts.com">  W3layouts</a></p>
        </div>
    </div>
</div>

Online_Boutique/Online_Boutique/Views/MyHome/HeaderPartial.cshtml
@using Online_Boutique.Models.MyModels;
@model List<LoaiSanPham>
 <!-- header-section-starts va thanh menu -->
    <div class="header">
        <div class="header-top-strip">
            <div class="container">
                <div class="header-top-left">
                    @if(Session["user"] == null)
                    {
                    <ul>
                        <li><a href="@Url.Action("DangNhap", "MyUsers")"><span class="glyphicon glyphicon-user"> </span>Login</a></li>
                        <li><a href="@Url.Action("DangKi","MyUsers")"><span class="glyphicon glyphicon-lock"> </span>Create an Account</a></li>
                    </ul>
                    }
                    @if (Session["user"] != null)
                    {
                    <ul>
                        <li><a href="#"><span class="glyphicon glyphicon-user">@Session["fullname"] </span></a></li>
                        <li><a href="~/MyUsers/Logout"><span class="glyphicon glyphicon-lock"> </span>Logout</a></li>
                    </ul>
                    }
                </div>
                <div class="header-right">
                    <div class="cart box_1">
                        <a href="@Url.Action("GioHang","MyCart")">
                            
                            <h3>@ViewBag.tongtien VNĐ (@ViewBag.soluong)<img src="/Content/web/images/bag.png" alt=""></h3>
                        </a>
                        <p><a href="~/MyCart/XoaTatCaGioHang" class="simpleCart_empty">Empty cart</a></p>
                        <div class="clearfix"> </div>
                    </div>
                </div>
               
                <div class="clearfix"> </div>
                
            </div>
            
        </div>
    </div>
    <!-- header-section-ends -->
   
    <div class="banner-top">
        <div class="container">
            <nav class="navbar navbar-default" role="navigation">
                <div class="navbar-header" style="width:150px;">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="logo">
                      
                            <h1 style="display:inline;"><a href="@Url.Action("Index","MyHome")"><span>E</span> -Shop</a></h1>
                    </div>
                   
                    
                </div>
                <!--/.navbar-header-->

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                    
                        <li>
                            @using (Html.BeginForm("KetQuaTimKiem","MySearchProducts",FormMethod.Post))
                            {
                                @Html.TextBox("txttimkiem", "", htmlAttributes: new { @class = "txttk_class", @placeholder = "Tìm kiếm sản phẩm, thương hiệu...", @style = "width:370px; height:42px;margin-right:270px;" })
                            }
                        </li>
                        <li class="dropdown">
                            <a href="@Url.Action("HeaderPartial","MyHome",new {@gt= "nu"})" class="dropdown-toggle" data-toggle="dropdown">Women <b class="caret"></b></a>
                            <ul class="dropdown-menu multi-column columns-3" style="min-width:120px;">
                                <div class="row">
                                    <div class="col-sm-1">
                                        <ul class="multi-column-dropdown">
                                            
                                            @{ 
                                                foreach (var item in Model)
                                                {
                                           
                                                    <li><a href="@Url.Action("LoaiSP","MyProducts",new {@maloaisp=@item.maloaisp})">@item.tenloaisp</a></li>
                                                }

                                             }
                          
                                        </ul>
                                    </div>
                                   
                                    <div class="clearfix"></div>
                                </div>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="@Url.Action("HeaderPartial","MyHome",new {@gt="nam" })" class="dropdown-toggle" data-toggle="dropdown">Men <b class="caret"></b></a>
                            <ul class="dropdown-menu multi-column columns-3" style="min-width:110px;">
                                <div class="row">
                                    <div class="col-sm-1">
                                        <ul class="multi-column-dropdown">

                                            @{
                                                foreach (var item in Model)
                                                {

                                                    <li><a href="@Url.Action("LoaiSP","MyProducts",new {@maloaisp=@item.maloaisp})">@item.tenloaisp</a></li>
                                                }

                                            }

                                        </ul>

                                    </div>
                                    <div class="clearfix"></div>
                                 </div>
                            </ul>
                        </li>
                        @*<li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">kids <b class="caret"></b></a>
                            <ul class="dropdown-menu multi-column columns-2">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <ul class="multi-column-dropdown">
                                            <li><h6>NEW IN</h6></li>
                                            <li><a href="products.html">New In Boys Clothing</a></li>
                                            <li><a href="products.html">New In Girls Clothing</a></li>
                                            <li><a href="products.html">New In Boys Shoes</a></li>
                                            <li><a href="products.html">New In Girls Shoes</a></li>
                                        </ul>
                                    </div>
                                    <div class="col-sm-6">
                                        <ul class="multi-column-dropdown">
                                            <li><h6>ACCESSORIES</h6></li>
                                            <li><a href="products.html">Bags</a></li>
                                            <li><a href="products.html">Watches</a></li>
                                            <li><a href="products.html">Sun Glasses</a></li>
                                            <li><a href="products.html">Jewellery</a></li>
                                        </ul>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </ul>
                        </li>*@
                       
                        <li><a href="contact.html">CONTACT</a></li>
                    </ul>
                </div>
                <!--/.navbar-collapse-->
            </nav>
            <!--/.navbar-->
        </div>
    </div>
<!-- header-section-va thanh menu ends -->

Online_Boutique/Online_Boutique/Views/MyHome/Index.cshtml
@using Online_Boutique.Models.MyModels;
@model List<SanPham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/TrangChu_Layout.cshtml";
}

<!--phần dưới cái banner...TẠI VÌ MỖI PARTIAL VIẾT ĐC CÓ 1 LOẠI TRUY VẤN ????-->
<div class="container">
    <div class="main-content">
        <div class="online-strip">
            <div class="col-md-4 follow-us">
                <h3>follow us : <a class="twitter" href="#"></a><a class="facebook" href="#"></a></h3>
            </div>
            <div class="col-md-4 shipping-grid">
                <div class="shipping">
                    <img src="~/Content/web/images/shipping.png" alt="" />
                </div>
                <div class="shipping-text">
                    <h3>Free Shipping</h3>
                    <p>on orders over $ 199</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="col-md-4 online-order">
                <p>Order online</p>
                <h3>Tel:999 4567 8902</h3>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="products-grid">
            <header>
                <h3 class="head text-center">Xu Hướng-Sản Phẩm Mới</h3>
            </header>
            @{ 
                foreach (var item in Model)
                {
                    <div class="col-md-4 product simpleCart_shelfItem text-center">
                        <a href="@Url.Action("ChiTietSP","MyProducts",new {@masp=@item.masp})"><img src="@Url.Content("~/HinhAnh/nu/"+@item.anhsp)" class="anhsp" alt="" /></a>
                        <div class="mask">
                            <a href="@Url.Action("ChiTietSP","MyProducts",new {@masp=@item.masp})">chi tiết</a>
                        </div>
                        <a class="product_name" href="@Url.Action("ChiTietSP","MyProducts",new {@masp=@item.masp})">@item.tensp</a>
                        <p><a class="item_add" href="@Url.Action("ThemGioHang","MyCart",new {@masp= @item.masp, @url= Request.Url.ToString() })"><i></i> <span class="item_price">@item.giabansp VND</span></a></p>
                    </div>
                }
              }
            <div class="clearfix"></div>
        </div>
    </div>
</div>